import React from "react";
import { View, Text, StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";

export type DataSource = "live" | "simulated";

/**
 * Small chip indicating whether displayed prices are real market data
 * ("LIVE", teal) or generated by the simulated engine ("SIMULATED",
 * muted gold warning styling).
 */
export function DataSourceBadge({
  source,
  liveLabel = "LIVE",
}: {
  source?: DataSource;
  liveLabel?: string;
}) {
  const simulated = source === "simulated";
  return (
    <View
      style={[styles.badge, { backgroundColor: simulated ? Colors.goldDim : Colors.accentDim }]}
      accessibilityLabel={simulated ? "Simulated prices" : "Live prices"}
    >
      <View style={[styles.dot, { backgroundColor: simulated ? Colors.gold : Colors.accent }]} />
      <Text style={[styles.text, { color: simulated ? Colors.gold : Colors.accent }]}>
        {simulated ? "SIMULATED" : liveLabel}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  dot: { width: 5, height: 5, borderRadius: 3 },
  text: { fontSize: 9, fontFamily: "Inter_700Bold", letterSpacing: 0.5 },
});

export default DataSourceBadge;
